version: '3.9'

networks:
  public:
    driver: bridge


services:

  eureka-server:
    build:
      context: ./cloud/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    networks:
      - public
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s


  api-gateway:
    build:
      context: ./cloud/gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - public
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s


  dental-lab-service:
    build:
      context: ./dental-service
      dockerfile: Dockerfile
    container_name: dental-lab-service
    networks:
      - public
    ports:
      - "8079:8000"
    environment:
      - PROJECT_VARIABLES_KEYCLOAK_URL=http://localhost:8080
      - PROJECT_VARIABLES_KEYCLOAK_REALM=dental-lab
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-ID=${KEYCLOAK_CLIENT_ID}
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-SECRET=${KEYCLOAK_CLIENT_SECRET}
      - PROJECT_VARIABLES_KEYCLOAK_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - PROJECT_VARIABLES_KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PROJECT_VARIABLES_DATASOURCE_URL=postgres:5432
      - PROJECT_VARIABLES_DATASOURCE_DATABASE=dental_lab
      - PROJECT_VARIABLES_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - PROJECT_VARIABLES_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - PROJECT_VARIABLES_REDIS_HOST=redis
      - PROJECT_VARIABLES_REDIS_PORT=6379
      - PROJECT_VARIABLES_MAIL_SMTP_HOST=smtp.yandex.ru
      - PROJECT_VARIABLES_MAIL_PORT=587
      - PROJECT_VARIABLES_MAIL_SERVICE_USER=${MAIL_SERVICE_USER}
      - PROJECT_VARIABLES_MAIL_SERVICE_PASSWORD=${MAIL_SERVICE_PASSWORD}
      - PROJECT_VARIABLES_MAIL_PROTOCOL=smtp
      - PROJECT_VARIABLES_MAIL_MAILRU=${VARIABLE_MAIL_MAILRU}
      - PROJECT_VARIABLES_MINIO_URL=http://minio:9000
      - PROJECT_VARIABLES_MINIO_ACCESS-KEY=${MINIO_ROOT_USERNAME}
      - PROJECT_VARIABLES_MINIO_SECRET-KEY=${MINIO_ROOT_PASSWORD}
      - PROJECT_VARIABLES_MINIO_BUCKET=dental-lab
      - PROJECT_VARIABLES_MINIO_DURATION-MINUTES=30
      - PROJECT_ENCRYPTION_SECRET-KEY=${ENCRYPTION_SECRET}
      - PROJECT_VARIABLES_SERVICE-API-URL=http://localhost:8082
      - PROJECT_VARIABLES_SERVICE-LABEL=Dental-Lab-Service
      - PROJECT_VARIABLES_SERVICE-URL=http://localhost:8081/dental-lab
      - PROJECT_VARIABLES_TELEGRAM-BOT_URL=http://telegram-bot:8083
      - PROJECT_VARIABLES_TEMPO_URL=http://tempo:4318/v1/traces
    depends_on:
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s


  ui-application:
    build:
      context: ./ui-mvc-app
      dockerfile: Dockerfile
    container_name: ui-application
    networks:
      - public
    ports:
      - "8081:8081"
    environment:
      - PROJECT_VARIABLES_KEYCLOAK_URL=http://keycloak:8080
      - PROJECT_VARIABLES_KEYCLOAK_REALM=dental-lab
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-ID=${KEYCLOAK_CLIENT-ID}
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-SECRET=${KEYCLOAK_CLIENT-SECRET}
      - PROJECT_VARIABLES_KEYCLOAK_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - PROJECT_VARIABLES_KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PROJECT_VARIABLES_KEYCLOAK_SERVICE-CLIENT-ID=${KEYCLOAK_UI_MVC_SERVICE_CLIENT_ID}
      - PROJECT_VARIABLES_KEYCLOAK_SERVICE-CLIENT-SECRET=${KEYCLOAK_UI_MVC_SERVICE_CLIENT_SECRET}
      - PROJECT_VARIABLES_REDIS_HOST=redis
      - PROJECT_VARIABLES_REDIS_PORT=6379
      - PROJECT_VARIABLES_DENTAL-LAB-API_URL=http://dental-lab-service:8082/api/v1
    depends_on:
      dental-lab-service:
        condition: service_healthy
      keycloak:
        condition: service_started
      redis:
        condition: service_started


  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    networks:
      - public
    expose:
      - "8083"
    depends_on:
      dental-lab-service:
        condition: service_healthy
      redis:
        condition: service_started


  postgres:
    container_name: dental_db
    image: postgres:15.3-alpine
    networks:
      - public
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
      - ./config/postgesql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  keycloak:
    container_name: dental_keycloak
    image: quay.io/keycloak/keycloak:25.0
    command: start
    networks:
      - public
    environment:
      - KC_HOSTNAME=localhost
      #      - KC_HOSTNAME_ADMIN_URL=https://dental-lab-service.ru/kc
      #      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KC_CACHE=local
      - KC_CACHE_STACK=simple
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/keycloak/realms:/opt/keycloak/data/import
      - ./config/keycloak/themes:/opt/keycloak/themes


  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - public
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      #      - MINIO_BROWSER_REDIRECT_URL=https://s3-photo.dental-lab-service.ru/minio-console
      #      - MINIO_SERVER_URL=https://s3-photo.dental-lab-service.ru
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - ./volumes/minio_data:/data


  redis:
    container_name: dental_redis
    image: redis:latest
    networks:
      - public
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/data:/data


  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    networks:
      - public
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.54.1
    networks:
      - public
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  loki:
    container_name: loki
    image: grafana/loki:3.1.1
    networks:
      - public
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml

  tempo:
    container_name: tempo
    image: grafana/tempo:2.6.1
    networks:
      - public
    ports:
      - "3200:3200"
      - "4318:4318"
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo.yml

  promtail:
    container_name: promtail
    image: grafana/promtail:3.1.1
    volumes:
      - ./logs:/logs
      - ./config/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
