version: '3.9'

networks:
  public:
    driver: bridge


services:

  eureka-server:
    build:
      context: .
      dockerfile: ./cloud/eureka-server/Dockerfile
    container_name: eureka-server
    networks:
      - public
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s


  postgres:
    container_name: dental_db
    image: postgres:15.3-alpine
    networks:
      - public
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
      - ./config/postgesql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  keycloak:
    container_name: dental_keycloak
    image: quay.io/keycloak/keycloak:25.0
    command: start
    networks:
      - public
    environment:
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KC_CACHE=local
      - KC_CACHE_STACK=simple
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/keycloak/realms:/opt/keycloak/data/import
      - ./config/keycloak/themes:/opt/keycloak/themes
    healthcheck:
      test: [ "CMD-SHELL", "curl --head -fsS http://localhost:9000/health/ready | echo $?" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - public
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - ./volumes/minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    container_name: dental_redis
    image: redis:latest
    networks:
      - public
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
      - public
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    networks:
      - public
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - promtail
      - tempo


  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.54.1
    networks:
      - public
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  loki:
    container_name: loki
    image: grafana/loki:3.1.1
    networks:
      - public
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml


  tempo:
    container_name: tempo
    image: grafana/tempo:2.6.1
    networks:
      - public
    ports:
      - "3200:3200"
      - "4318:4318"
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo.yml


  promtail:
    container_name: promtail
    image: grafana/promtail:3.1.1
    volumes:
      - ./logs:/logs
      - ./config/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
