version: '3.9'

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true


services:

  dental-lab-service:
    build:
      context: ./dental-service
      dockerfile: Dockerfile
    container_name: dental-lab-service
    networks:
      - public
      - internal
    expose:
      - "8082"
    environment:
      - PROJECT_VARIABLES_KEYCLOAK_URL=https://dental-lab-service.ru/kc
      - PROJECT_VARIABLES_KEYCLOAK_REALM=dental-lab
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-ID=dental-lab-client
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-SECRET=???
      - PROJECT_VARIABLES_KEYCLOAK_USERNAME=admin
      - PROJECT_VARIABLES_KEYCLOAK_PASSWORD=???
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK-SET-URI=https://dental-lab-service.ru/kc/realms/dental-lab/protocol/openid-connect/certs
      - PROJECT_VARIABLES_DATASOURCE_URL=postgres:5432
      - PROJECT_VARIABLES_DATASOURCE_DATABASE=dental_lab
      - PROJECT_VARIABLES_DATASOURCE_USERNAME=postgres
      - PROJECT_VARIABLES_DATASOURCE_PASSWORD=???
      - PROJECT_VARIABLES_REDIS_HOST=redis
      - PROJECT_VARIABLES_REDIS_PORT=6379
      - PROJECT_VARIABLES_MAIL_SMTP_HOST=smtp.yandex.ru
      - PROJECT_VARIABLES_MAIL_PORT=587
      - PROJECT_VARIABLES_MAIL_SERVICE_USER=???
      - PROJECT_VARIABLES_MAIL_SERVICE_PASSWORD=???
      - PROJECT_VARIABLES_MAIL_PROTOCOL=smtp
      - PROJECT_VARIABLES_MAIL_MAILRU=777s999_79@mail.ru
      - PROJECT_VARIABLES_MINIO_URL=https://s3-photo.dental-lab-service.ru
      - PROJECT_VARIABLES_MINIO_ACCESS-KEY=minioadmin
      - PROJECT_VARIABLES_MINIO_SECRET-KEY=???
      - PROJECT_VARIABLES_MINIO_BUCKET=dental-lab
      - PROJECT_VARIABLES_MINIO_DURATION-MINUTES=30
      - PROJECT_ENCRYPTION_SECRET-KEY=???
      - PROJECT_VARIABLES_ADMIN-EMAIL=???
      - PROJECT_VARIABLES_SERVICE-LABEL=Dental-Lab-Service
      - PROJECT_VARIABLES_TELEGRAM-BOT_URL=http://telegram-bot:8083
    depends_on:
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 20s


  ui-application:
    build:
      context: ./ui-mvc-app
      dockerfile: Dockerfile
    container_name: ui-application
    networks:
      - public
      - internal
    expose:
      - "8081"
    environment:
      - PROJECT_VARIABLES_KEYCLOAK_URL=https://dental-lab-service.ru/kc
      - PROJECT_VARIABLES_KEYCLOAK_REALM=dental-lab
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-ID=dental-lab-client
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-SECRET=???
      - PROJECT_VARIABLES_KEYCLOAK_USERNAME=admin
      - PROJECT_VARIABLES_KEYCLOAK_PASSWORD=???
      - PROJECT_VARIABLES_KEYCLOAK_SERVICE-CLIENT-ID=ui-mvc-client
      - PROJECT_VARIABLES_KEYCLOAK_SERVICE-CLIENT-SECRET=???
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION-URI=https://dental-lab-service.ru/kc/realms/dental-lab/protocol/openid-connect/auth
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN-URI=https://dental-lab-service.ru/kc/realms/dental-lab/protocol/openid-connect/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER-INFO-URI=https://dental-lab-service.ru/kc/realms/dental-lab/protocol/openid-connect/userinfo
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK-SET-URI=https://dental-lab-service.ru/kc/realms/dental-lab/protocol/openid-connect/certs
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER-NAME-ATTRIBUTE=preferred_username
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT-URI=https://dental-lab-service.ru/login/oauth2/code/keycloak
      - PROJECT_VARIABLES_REDIS_HOST=redis
      - PROJECT_VARIABLES_REDIS_PORT=6379
      - PROJECT_VARIABLES_ADMIN-EMAIL=???
      - PROJECT_VARIABLES_DENTAL-LAB-API_URL=http://dental-lab-service:8082/api/v1
    depends_on:
      dental-lab-service:
        condition: service_healthy
      keycloak:
        condition: service_started
      redis:
        condition: service_started


  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    networks:
      - public
      - internal
    expose:
      - "8083"
    environment:
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-ID=telegram-bot-client
      - PROJECT_VARIABLES_KEYCLOAK_CLIENT-SECRET=???
      - PROJECT_VARIABLES_REDIS_HOST=redis
      - PROJECT_VARIABLES_REDIS_PORT=6379
      - PROJECT_VARIABLES_DENTAL-LAB-API_URL=http://dental-lab-service:8082/api/v1
      - PROJECT_VARIABLES_DENTAL-LAB-SITE_URL=https://dental-lab-service.ru
      - PROJECT_VARIABLES_TELEGRAM_USERNAME=dental_mechanic_service_bot
      - PROJECT_VARIABLES_TELEGRAM_BOT-TOKEN=???
      - PROJECT_VARIABLES_TELEGRAM-LINK-DURATION-MINUTES=10
      - PROJECT_VARIABLES_TELEGRAM-OTP-LENGTH=7
    depends_on:
      dental-lab-service:
        condition: service_healthy
      redis:
        condition: service_started


  postgres:
    container_name: dental_db
    image: postgres:15.3-alpine
    networks:
      - internal
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=???
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
      - ./config/postgesql/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  keycloak:
    container_name: dental_keycloak
    image: quay.io/keycloak/keycloak:25.0
    command: start --import-realm
    networks:
      - public
      - internal
    environment:
      - KC_HOSTNAME=https://dental-lab-service.ru/kc
      - KC_HOSTNAME_ADMIN_URL=https://dental-lab-service.ru/kc
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KC_CACHE=local
      - KC_CACHE_STACK=simple
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=???
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=???
    expose:
      - '8080'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config/keycloak/realms:/opt/keycloak/data/import
      - ./config/keycloak/themes:/opt/keycloak/themes


  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - public
      - internal
    expose:
      - "9000"
    ports:
      - "9001:9001"
    environment:
      - MINIO_BROWSER_REDIRECT_URL=https://s3-photo.dental-lab-service.ru/minio-console
      - MINIO_SERVER_URL=https://s3-photo.dental-lab-service.ru
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=???
    command: server --console-address ":9001" /data
    volumes:
      - ./volumes/minio_data:/data


  redis:
    container_name: dental_redis
    image: redis:latest
    networks:
      - internal
    expose:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/data:/data


  # ==================== Nginx ====================
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - public
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  # ==================== Certbot ====================
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
