server:
  port: 8082

spring:
  application:
    name: dental-lab-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${project.variables.datasource.url}/${project.variables.datasource.database}
    username: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://${project.variables.datasource.url}/${project.variables.datasource.database}
    user: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    host: ${project.variables.mail.smtp.host}
    port: ${project.variables.mail.port}
    username: ${project.variables.mail.service.user}
    password: ${project.variables.mail.service.password}
    protocol: ${project.variables.mail.protocol}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      environment: production
    distribution:
      percentiles-histogram:
        http.server.requests: true

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: ${project.variables.alloy.url}
  traces:
    exporter: otlp
    sampler: always_on
  metrics:
    exporter: none
  logs:
    exporter: none
