server:
  port: 8082

spring:
  application:
    name: dental-lab-service
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${project.variables.datasource.url}/${project.variables.datasource.database}
    username: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://${project.variables.datasource.url}/${project.variables.datasource.database}
    user: ${project.variables.datasource.username}
    password: ${project.variables.datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    host: ${project.variables.mail.smtp.host}
    port: ${project.variables.mail.port}
    username: ${project.variables.mail.service.user}
    password: ${project.variables.mail.service.password}
    protocol: ${project.variables.mail.protocol}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  info:
    title: Dental Lab Service
    description: Open API for Dental Lab Service
    version: 1.0.0
    url:
  swagger-ui:
    path: /index.html
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  paths-to-match: /api/v1/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${project.variables.tempo.url}
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  file:
    name: logs/application.log