server:
  port: 8081
  servlet:
    context-path: /dental-lab
    session:
      cookie:
        secure: false
        http-only: true

spring:
  application:
    name: ui-application
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  thymeleaf:
    cache: true
  web:
    resources:
      static-locations: classpath:/static/
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${project.variables.keycloak.client-id}
            client-secret: ${project.variables.keycloak.client-secret}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG
