server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

spring:
  application:
    name: ui-application
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  thymeleaf:
    cache: true
  web:
    resources:
      static-locations: classpath:/static/
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${project.variables.keycloak.client-id}
            client-secret: ${project.variables.keycloak.client-secret}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}

project:
  variables:
    dental-lab-api:
      url: http://localhost:8082/api/v1
    keycloak:
      url: http://localhost:8080
      username: admin
      password: admin
      realm: dental-lab
      client-id: dental-lab-client
      client-secret: 9S95xSQgkdxbt9VxNPdHoULyTyaLZIWG
      service-client-id: ui-mvc-client
      service-client-secret: k2tMAw4AVOzZbcW8MuUFiQUjDHx4ZMDz
    redis:
      host: localhost
      port: 6379
