server:
  port: 8081
  servlet:
    context-path: /dental-lab
    session:
      cookie:
        secure: false
        http-only: true

spring:
  application:
    name: ui-application
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  thymeleaf:
    cache: true
  web:
    resources:
      static-locations: classpath:/static/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
