server:
  port: 8081
  servlet:
    context-path: /dental-lab

spring:
  application:
    name: ui-application
  thymeleaf:
    cache: true
  web:
    resources:
      static-locations: classpath:/static/

project:
  variables:
    dental-lab-url: http://localhost:8082/api/v1