package org.lab.telegram_bot.domain.command;

public enum TextKeys {

    SELECT_PRODUCT_TYPE_TO_UPDATE,
    INPUT_NEW_PRICE_FOR_PRODUCT_TYPE,
    SELECT_PRODUCT_TYPE_TO_DELETE,
    NEW_DENTAL_WORK,
    SELECT_PRODUCT_TYPE_FOR_WORK,
    INPUT_QUANTITY_FOR_PRODUCT,
    ADD_PRODUCT_TO_DENTAL_WORK,
    DELETE_PRODUCT_FROM_DENTAL_WORK,
    INPUT_QUANTITY_AND_COMPLETION_DATE_FOR_PRODUCT,
    INPUT_WORK_ID_TO_OPEN,
    SELECT_FIELD_TO_UPDATE,
    INPUT_NEW_VALUE_FOR_FIELD,
    SELECT_PRODUCT_FOR_UPDATE_COMPLETION,
    INPUT_NEW_COMPLETION_DATE_FOR_PRODUCT,
    SELECT_PRODUCT_FOR_DELETE,
    DELETE_DENTAL_WORK,
    DENTAL_WORK_IS_DELETED,
    SELECT_MONTH_FOR_REPORT,
    INPUT_ANOTHER_MONTH_FOR_REPORT,
    SELECT_MONTH_TO_COUNT_PROFIT,
    INPUT_VALUE_FOR_SEARCH,
    UPLOAD_PHOTO_TO_CHAT,
    PHOTO_IS_ADDED,
    PHOTO_IS_FAILED,
    EMPTY;


    public enum WorkFields {
        PATIENT,
        CLINIC,
        STATUS,
        COMPLETION,
        COMMENT
    }
}
