server:
  port: 8083

spring:
  application:
    name: telegram-bot
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}

telegram:
  api:
    path: "https://api.telegram.org/file/bot"

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://alloy:4318
  traces:
    exporter: otlp
    sampler: always_on
  metrics:
    exporter: none
  logs:
    exporter: none
