server:
  port: 8083

spring:
  application:
    name: telegram-bot
  profiles:
    active: local
  redis:
    host: ${project.variables.redis.host}
    port: ${project.variables.redis.port}
  rabbitmq:
    host: ${project.variables.rabbitmq.host}
    port: ${project.variables.rabbitmq.port}
    username: ${project.variables.rabbitmq.username}
    password: ${project.variables.rabbitmq.password}
    topic: dental-lab-events
    queue: mailing-events
    routing-key: works-for-tomorrow
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
telegram:
  api:
    path: "https://api.telegram.org/file/bot"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${project.variables.tempo.url}
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  file:
    name:


project:
  variables:
    dental-lab-api:
      url: http://localhost:8082/api/v1
    dental-lab-site:
      url: http://localhost:8081/
    redis:
      host: localhost
      port: 6379
    telegram:
      username: dental_lab_service_bot
      bot-token: ????????
    keycloak:
      url: http://localhost:8080
      realm: dental-lab
      client-id: telegram-bot-client
      client-secret: lRPMOwOylXUUhlUXcHYqye92jLLZh11R
    tempo:
      url: http://localhost:4318/v1/traces
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  telegram:
    link-duration-minutes: 10
    otp-length: 7
    proxy:
      enable: false
      host: "127.0.0.1"
      port: 10808
      type: HTTP
