server:
  port: 8082

spring:
  application:
    name: api-gateway
  profiles:
    active: local
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://host.docker.internal:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dental-lab-service
          uri: lb://dental-lab-service
          predicates:
            - Path=/api/v1/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${project.variables.keycloak.url}/realms/${project.variables.keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: ${project.variables.eureka-server.url}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
